# Generated by Django 4.1.7 on 2023-03-11 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Booknow', '0010_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedcar',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookedcar',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
