# Generated by Django 4.1.7 on 2023-03-11 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booknow', '0012_remove_bookedcar_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedcar',
            name='date',
            field=models.DateTimeField(default=0, verbose_name=datetime.date(2023, 3, 11)),
            preserve_default=False,
        ),
    ]
