# Generated by Django 4.1.7 on 2023-03-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booknow', '0013_bookedcar_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedcar',
            name='date',
            field=models.DateTimeField(default='11032023'),
        ),
    ]
