# Generated by Django 4.1.7 on 2023-03-11 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booknow', '0014_alter_bookedcar_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedcar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 6, 2, 23, 723837, tzinfo=datetime.timezone.utc)),
        ),
    ]
