# Generated by Django 4.1.7 on 2023-03-11 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Booknow', '0017_remove_bookedcar_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedcar',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
